#homework_1 Problem_2
  The following code were wrote with Pytorch Tutorial from Muzhe Guo:
  https://github.com/Mooozer/STAT6289/blob/master/STATS6289_DL_pytorch_Presentation_MuzheGuo.ipynb
  I made several modifications. And they are highlighted with comments.




python objects

In [1]:
[1,2,3]

[1, 2, 3]

In [2]:
(1,2,3)

(1, 2, 3)

In [3]:
{1,2,3,4,"a","a","s",2,3,4}

{1, 2, 3, 4, 'a', 's'}

In [4]:
d= {"a":1, "b":2, "c":3}
d["a"]

1

In [3]:
for i in range(5):
    print(i)

0
1
2
3
4


In [5]:
import torch
print(torch.__version__)

1.6.0+cu101


In [6]:
a = torch.tensor([1, 2, 3])
print(a)
print(type(a))
print(a.dim())
print( a.shape)

print( a[0])
print( type(a[0]))
print( type(a[0].item()))


a[1] = 10
print(a)

tensor([1, 2, 3])
<class 'torch.Tensor'>
1
torch.Size([3])
tensor(1)
<class 'torch.Tensor'>
<class 'int'>
tensor([ 1, 10,  3])


In [7]:
b = torch.tensor([[1, 2, 3], [6, 6, 6]])
print(b)
print( b.dim())
print( b.shape)

print('b[0, 1]:', b[0, 1])
print('b[1, 2]:', b[1, 2])


b[1, 1] = 100
print(b)

tensor([[1, 2, 3],
        [6, 6, 6]])
2
torch.Size([2, 3])
b[0, 1]: tensor(2)
b[1, 2]: tensor(6)
tensor([[  1,   2,   3],
        [  6, 100,   6]])


In [8]:

a = torch.zeros(3,4)
print(a)


b = torch.ones(2, 2)
print(b)


c = torch.eye(4)
print(c)

d = torch.rand(4, 6) #random value between [0,1] with shape (4,6)
print(d)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[0.2944, 0.4118, 0.5540, 0.5077, 0.5118, 0.5245],
        [0.2273, 0.4473, 0.4604, 0.6484, 0.3166, 0.5398],
        [0.5697, 0.5554, 0.8023, 0.8377, 0.7979, 0.8640],
        [0.0216, 0.5765, 0.6001, 0.6504, 0.3339, 0.7889]])


In [9]:
x0 = torch.tensor([1, 2])  
x1 = torch.tensor([1., 2.]) 
x2 = torch.tensor([1., 2]) 
print(x0.dtype)
print(x1.dtype)
print(x2.dtype)

#asign different datatypes
y0 = torch.tensor([1, 2], dtype=torch.float32)  
y1 = torch.tensor([1, 2], dtype=torch.int32)    
y2 = torch.tensor([1, 2], dtype=torch.int64)   
print( y0.dtype)
print( y1.dtype)
print( y2.dtype)


torch.int64
torch.float32
torch.float32
torch.float32
torch.int32
torch.int64


In [22]:
x0 = torch.eye(3, dtype=torch.int64)
x1 = x0.float()  
x2 = x0.double() 
x3 = x0.to(torch.float32) 
x4 = x0.to(torch.float64) 
print('x0:', x0.dtype)
print('x1:', x1.dtype)
print('x2:', x2.dtype)
print('x3:', x3.dtype)
print('x4:', x4.dtype)

x0: torch.int64
x1: torch.float32
x2: torch.float64
x3: torch.float32
x4: torch.float64


In [31]:
x0 = torch.eye(4, dtype=torch.float64) 
x1 = torch.zeros_like(x0)              
x2 = x0.new_zeros(1,2)              
x3 = torch.ones(3, 4).to(x0)    
print('x0 shape is %r, dtype is %r' % (x0.shape, x0.dtype))
print('x1 shape is %r, dtype is %r' % (x1.shape, x1.dtype))
print('x2 shape is %r, dtype is %r' % (x2.shape, x2.dtype))
print('x3 shape is %r, dtype is %r' % (x3.shape, x3.dtype))
x3

x0 shape is torch.Size([4, 4]), dtype is torch.float64
x1 shape is torch.Size([4, 4]), dtype is torch.float64
x2 shape is torch.Size([1, 2]), dtype is torch.float64
x3 shape is torch.Size([3, 4]), dtype is torch.float64


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

2.Tensor indexing

In [32]:
a = torch.tensor([1, 2, 3, 4, 5, 6, 7])
print(0, a)      
print(1, a[2:5])   
print(2, a[2:])   
print(3, a[:5])    
print(4, a[:])     
print(5, a[1:5:2]) 
print(6, a[:-1])   
print(7, a[-4::2]) 

0 tensor([1, 2, 3, 4, 5, 6, 7])
1 tensor([3, 4, 5])
2 tensor([3, 4, 5, 6, 7])
3 tensor([1, 2, 3, 4, 5])
4 tensor([1, 2, 3, 4, 5, 6, 7])
5 tensor([2, 4])
6 tensor([1, 2, 3, 4, 5, 6])
7 tensor([4, 6])


In [40]:

a = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a.shape)

print(a[1, :])
print(a[1]) 
print(a[:, 2])
print(a[:2, -3:])
print(a[::2, 1:3])
print(a[1,1:3])

torch.Size([3, 4])
tensor([5, 6, 7, 8])
tensor([5, 6, 7, 8])
tensor([ 3,  7, 11])
tensor([[2, 3, 4],
        [6, 7, 8]])
tensor([[ 2,  3],
        [10, 11]])
tensor([6, 7])


In [42]:
a = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

row_r1 = a[1, :]   #second row of a 
row_r2 = a[1:2, :]  #1 row and 4 column
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

Original tensor
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([5, 6, 7, 8]) torch.Size([4])
tensor([[5, 6, 7, 8]]) torch.Size([1, 4])
tensor([ 2,  6, 10]) torch.Size([3])
tensor([[ 2],
        [ 6],
        [10]]) torch.Size([3, 1])


In [44]:
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
b = a[0, 1:]
c = a[0, 1:].clone()
print(a)
print(b)
print(c)

a[0, 1] = 20  # a[0, 1] and b[0] point to the same element
b[1] = 100    # b[1] and a[0, 2] point to the same element
c[2] = 40     # c is a clone, so it has its own data
print('\nAfter mutating:')
print(a)
print(b)
print(c)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([2, 3, 4])
tensor([2, 3, 4])

After mutating:
tensor([[  1,  20, 100,   4],
        [  5,   6,   7,   8]])
tensor([ 20, 100,   4])
tensor([ 2,  3, 40])


# **modification_1**: try not to use 'idx'
the results are the same.

In [52]:
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)


idx = [0, 0, 2, 1, 1]  
print('\nReordered rows:')
print(a[[1,1,2,0,0]])
print(a[idx])

idx = torch.tensor([3, 2, 1, ]) 
print('\nReordered columns:')
print(a[:, idx])
print(a[:,[3,1]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Reordered rows:
tensor([[ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4]])
tensor([[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]])

Reordered columns:
tensor([[ 4,  3,  2],
        [ 8,  7,  6],
        [12, 11, 10]])
tensor([[ 4,  2],
        [ 8,  6],
        [12, 10]])


# **modification_2**: manually get the diagonal


In [69]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

idx = [0, 1, 2]
print(a[idx, idx])
print(a[[1,2],[1,2]])
a[idx, idx] =torch.tensor([11, 22, 33])
print(a)

tensor([1, 5, 9])
tensor([5, 9])
tensor([[11,  2,  3],
        [ 4, 22,  6],
        [ 7,  8, 33]])


In [78]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

idx0 = torch.arange(4)  # Quick way to build [0, 1, 2, 3]
idx1 = torch.tensor([0,2,1,1])
print(a[idx0, idx1])

a[idx0, idx1] = 0
print(a)

tensor([ 1,  6,  8, 11])
tensor([[ 0,  2,  3],
        [ 4,  5,  0],
        [ 7,  0,  9],
        [10,  0, 12]])


In [84]:
a = torch.tensor([[1,2], [3, 4], [5, 6]])
print(a)

mask = (a <= 3)
print(mask)

print(a[mask])

a[a == 3] = 0
print(a)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ True,  True],
        [ True, False],
        [False, False]])
tensor([1, 2, 3])
tensor([[1, 2],
        [0, 4],
        [5, 6]])


3.Reshaping operations

In [87]:
x0 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

x1 = x0.view(8)
print(x1)

x2 = x1.view(1, 8) #shape (1,8)
print(x2)
print('shape:', x2.shape)

x3 = x1.view(8, 1) #shape (8,1)
print(x3)
print('shape:', x3.shape)

x4 = x1.view(2, 2, 2) #shape(2,2,2)
print(x4)
print('shape:', x4.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
shape: torch.Size([1, 8])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])
shape: torch.Size([8, 1])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
shape: torch.Size([2, 2, 2])


In [89]:
x0 = torch.tensor([[1,4,6,2], [2,7,22,7]])
x1 = x0.view(-1, )
x2 = x0.view(-1, 2) # 2 columns

print(x0)
print(x1)
print(x2)

tensor([[ 1,  4,  6,  2],
        [ 2,  7, 22,  7]])
tensor([ 1,  4,  6,  2,  2,  7, 22,  7])
tensor([[ 1,  4],
        [ 6,  2],
        [ 2,  7],
        [22,  7]])


In [90]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [1,5,2]])
x_flat = x.view(-1)
print(x)
print(x_flat)

x[0, 0] = 10   
x_flat[1] = 20

print(x)
print(x_flat)
#both changed the values in x

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 5, 2]])
tensor([1, 2, 3, 4, 5, 6, 1, 5, 2])
tensor([[10, 20,  3],
        [ 4,  5,  6],
        [ 1,  5,  2]])
tensor([10, 20,  3,  4,  5,  6,  1,  5,  2])


In [92]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.view(3, 2))
print(torch.t(x))
print(x.t())

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [10]:
x0 = torch.tensor([
     [[1,  2,  3,  4],
      [5,  6,  7,  8],
      [9, 10, 11, 12]],
     [[13, 14, 15, 16],
      [17, 18, 19, 20],
      [21, 22, 23, 24]]])
print(x0)
print(x0.shape)

x1 = x0.transpose(1,2)
print(x1)
print(x1.shape)
x2 = x0.permute(2,0,1) #old dimension (2,0,1) at dimension (0,1,2) respectively
print(x2)
print('shape:', x2.shape)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
torch.Size([2, 3, 4])
tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]])
torch.Size([2, 4, 3])
tensor([[[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]],

        [[ 4,  8, 12],
         [16, 20, 24]]])
shape: torch.Size([4, 2, 3])


In [100]:
x0 = torch.randn(3,4,2)

try:
  x1 = x0.transpose(1, 2).view(8, 3)
except RuntimeError as e:
  print(type(e), e)
  
x1 = x0.transpose(1, 2).contiguous().view(8, 3)
x2 = x0.transpose(1, 2).reshape(8, 3)
print(x1.shape)
print(x2.shape)


<class 'RuntimeError'> view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
torch.Size([8, 3])
torch.Size([8, 3])


In [106]:
x = torch.tensor([[1, 2, 3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6, 7, 8]], dtype=torch.float32)
# Elementwise sum
print((x + y) == torch.add(x,y))
print(torch.add(x,y) == x.add(y))
# Elementwise difference
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

# Elementwise product
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

# Elementwise division
print(x / y)
print(torch.div(x, y))
print(x.div(y))

# Elementwise power
print(x ** y)
print(torch.pow(x, y))
print(x.pow(y))

tensor([[True, True, True, True]])
tensor([[True, True, True, True]])
tensor([[-4., -4., -4., -4.]])
tensor([[-4., -4., -4., -4.]])
tensor([[-4., -4., -4., -4.]])
tensor([[ 5., 12., 21., 32.]])
tensor([[ 5., 12., 21., 32.]])
tensor([[ 5., 12., 21., 32.]])
tensor([[0.2000, 0.3333, 0.4286, 0.5000]])
tensor([[0.2000, 0.3333, 0.4286, 0.5000]])
tensor([[0.2000, 0.3333, 0.4286, 0.5000]])
tensor([[1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]])
tensor([[1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]])
tensor([[1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]])


In [107]:
x = torch.tensor([[1, 2, 3, 4]], dtype=torch.float32)

print('Square root:')
print(torch.sqrt(x))
print(x.sqrt())

print('\nTrig functions:')
print(torch.sin(x))
print(x.sin())
print(torch.cos(x))
print(x.cos())

Square root:
tensor([[1.0000, 1.4142, 1.7321, 2.0000]])
tensor([[1.0000, 1.4142, 1.7321, 2.0000]])

Trig functions:
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568]])
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568]])
tensor([[ 0.5403, -0.4161, -0.9900, -0.6536]])
tensor([[ 0.5403, -0.4161, -0.9900, -0.6536]])


In [111]:
x = torch.tensor([[4, 5, 3], 
                  [41, 52, 6]])
print(torch.sum(x))
print(x.sum())

print(torch.sum(x, dim=0))
print(x.sum(dim=0))

print(torch.sum(x, dim=1))
print(x.sum(dim=1))

tensor(111)
tensor(111)
tensor([45, 57,  9])
tensor([45, 57,  9])
tensor([12, 99])
tensor([12, 99])


In [112]:
x = torch.tensor([[2, 4, 3, 5], [3, 3, 5, 2]], dtype=torch.float32)

print('\nOverall minimum: ', x.min())

col_min_vals, col_min_idxs = x.min(dim=0)
print('\nMinimum along each column:')
print('values:', col_min_vals)
print('idxs:', col_min_idxs)
 
row_min_vals, row_min_idxs = x.min(dim=1)
print('\nMinimum along each row:')
print('values:', row_min_vals)
print('idxs:', row_min_idxs)


Overall minimum:  tensor(2.)

Minimum along each column:
values: tensor([2., 3., 3., 2.])
idxs: tensor([0, 1, 0, 1])

Minimum along each row:
values: tensor([2., 2.])
idxs: tensor([0, 3])


In [115]:

x = torch.randn(4,5,6,7)
print(x.shape)


x = x.mean(dim=1)
print(x.shape)

x = x.sum(dim=2)
print(x.shape)

x = x.mean(dim=1, keepdim=True)
print(x.shape)

torch.Size([4, 5, 6, 7])
torch.Size([4, 6, 7])
torch.Size([4, 6])
torch.Size([4, 1])


In [118]:
v = torch.tensor([12,4], dtype=torch.float32)
w = torch.tensor([4,50], dtype=torch.float32)

print('Dot products:')
print(torch.dot(v, w))
print(v.dot(w))

# matrix-matrix products
x = torch.tensor([[4,5],[2,2]], dtype=torch.float32)
y = torch.tensor([[5,6],[9,1]], dtype=torch.float32)
print(torch.mm(x, y))
print(x.mm(y))

print(torch.mv(x, v))
print(x.mv(v))

Dot products:
tensor(248.)
tensor(248.)
tensor([[65., 29.],
        [28., 14.]])
tensor([[65., 29.],
        [28., 14.]])
tensor([68., 32.])
tensor([68., 32.])


5.Broadcasting

# **modification3:**


1.   change the shape of x to (5,3).

2.   add the code about add the vector b to each column of a



In [123]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12],[13,14,15]])
v = torch.tensor([10,20,30])
y = torch.zeros_like(x)  

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(5):
    y[i, :] = x[i, :] + v
print(y)

a = torch.tensor([[1,2,3],[2,2,2],[3,4,3],[10,10,10]])
b = torch.tensor([1,2,2,1])
c = torch.zeros_like(a)
# add the vector b to each column
for i in range(3):
  c[:,i] = a[:,i] + b
print(c)


tensor([[11, 22, 33],
        [14, 25, 36],
        [17, 28, 39],
        [20, 31, 42],
        [23, 34, 45]])
tensor([[ 2,  3,  4],
        [ 4,  4,  4],
        [ 5,  6,  5],
        [11, 11, 11]])


# **modification_4:**
do 'v.repeat(3,3)' and notice that the first variable indicates how many copies of v and return in row, while the second variable shows the number of copies by column.

In [129]:
v1 = v.repeat((5,1))
print(v1)
v2 = v.repeat(3,3)
print(v2)

tensor([[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]])
tensor([[10, 20, 30, 10, 20, 30, 10, 20, 30],
        [10, 20, 30, 10, 20, 30, 10, 20, 30],
        [10, 20, 30, 10, 20, 30, 10, 20, 30]])


In [131]:
y = x + v1
print(y)

tensor([[11, 22, 33],
        [14, 25, 36],
        [17, 28, 39],
        [20, 31, 42],
        [23, 34, 45]])


In [133]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([10, 0, 5])
y = x + v 
print(y)

tensor([[11,  2,  8],
        [14,  5, 11],
        [17,  8, 14],
        [20, 11, 17]])


# **modification_5:**
change the dimension of v. the number of columns of flattened vector should be the same as rows of w so that they are productable.


In [137]:

v = torch.tensor([[4,5,7,8],[3,4,5,8]])  
w = torch.tensor([12,4,5,5])     
print(v.view(8, 1) * w)

tensor([[48, 16, 20, 20],
        [60, 20, 25, 25],
        [84, 28, 35, 35],
        [96, 32, 40, 40],
        [36, 12, 15, 15],
        [48, 16, 20, 20],
        [60, 20, 25, 25],
        [96, 32, 40, 40]])


In [139]:
import torch

if torch.cuda.is_available:
  print('PyTorch can use GPUs!')
else:
  print('PyTorch cannot use GPUs.')

PyTorch can use GPUs!
